#!/bin/sh

# Setup for yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

# Install
sudo apt-get update
sudo apt-get install -y nodejs yarn zsh
